{% set name = "python-jose" %}
{% set version = "3.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55779b5e6ad599c6336191246e95eb2293a9ddebd555f796a65f838f07e5d78a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
    # required in setup_requires
    - pytest-runner
    - setuptools >=39.2.0
    - wheel
  run:
    - python >=3.6
    - ecdsa <1.0
    - six <2.0
    - future <1.0
    - pycryptodome >=3.3.1,<4.0.0
    - ecdsa !=0.15
    - rsa
    - pyasn1

test:
  imports:
    - jose
    - jose.backends
  requires:
    - pip
    - ecdsa !=0.15
    - pytest
    - pytest-cov
    - pytest-runner
    - python-jose
  commands:
    - pytest
  files:
    - usage.py
  source_files:
    - tests
  commands:
    - pip check
    - python usage.py
    - pytest -m "not (pycryptodome or pycrypto or backend_compatibility)" tests

about:
  home: http://github.com/mpdavis/python-jose
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: JOSE implementation in Python
  doc_url: https://python-jose.readthedocs.io/en/latest/
  dev_url: https://github.com/mpdavis/python-jose

extra:
  recipe-maintainers:
    - mariusvniekerk
