{% set name = "python-jose" %}
{% set version = "3.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_jose-{{ version }}.tar.gz
  sha256: fb4eaa44dbeb1c26dcc69e4bd7ec54a1cb8dd64d3b4d81ef08d90ff453f2b01b

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=39.2.0
    - wheel
  run:
    - python
    - ecdsa !=0.15
    - rsa >=4.0,<5.0,!=4.4,!=4.1.1
    - pyasn1 >=0.5.0
    # extras_require but nice to have for backwards compatibility
    - pycryptodome >=3.3.1,<4.0.0
  run_constrained:
    - cryptography >=3.4.0
    - pycrypto >=2.6.0,<2.7.0

test:
  imports:
    - jose
    - jose.backends
  requires:
    - pip
    - ecdsa !=0.15
    - pytest
    - pytest-cov
    - pytest-runner
    - python-jose
  files:
    - usage.py
  source_files:
    - tests
    - pytest.ini
  commands:
    - pip check
    - python usage.py
    - pytest -m "not (pycryptodome or pycrypto or backend_compatibility)" tests

about:
  home: https://github.com/mpdavis/python-jose
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: JOSE implementation in Python
  doc_url: https://python-jose.readthedocs.io/en/latest/
  dev_url: https://github.com/mpdavis/python-jose

extra:
  recipe-maintainers:
    - mariusvniekerk
