{% set name = "python-jose" %}
{% set version = "3.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e4192402e100b5fb09de5a8ea6bcc39c36ad4526341c123d401e2561720335b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    # required in setup_requires
    - pytest-runner
  run:
    - python
    - ecdsa <1.0
    - six <2.0
    - future <1.0
    - pycryptodome >=3.3.1,<4.0.0

test:
  imports:
    - jose

about:
  home: http://github.com/mpdavis/python-jose
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: JOSE implementation in Python
  doc_url: https://github.com/mpdavis/python-jose
  dev_url: https://github.com/mpdavis/python-jose

extra:
  recipe-maintainers:
    - mariusvniekerk
